name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Backend Steps
    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    - name: Build backend project
      run: npm run build
      working-directory: ./backend

    # - name: Run backend lint
    #   run: npm run lint
    #   working-directory: ./backend

    # Frontend Steps
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    # - name: Lint frontend code
    #   run: npm run lint
    #   working-directory: ./frontend

    - name: Build frontend project
      run: npm run build
      working-directory: ./frontend

    - name: Preview frontend build
      run: npm run preview
      working-directory: ./frontend
